{
  "incomplete_results": false, 
  "items": [
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Started to fail pretty consistently sometime after https://github.com/pytorch/pytorch/tree/4a2fb3404215c774fdf2805ba8d495bb7dc1bbbf \r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/236917/workflows/7f73ea98-2cfa-4a7c-b26e-2eaca2661f34/jobs/8801912/steps\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd", 
      "closed_at": null, 
      "comments": 0, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/47645/comments", 
      "created_at": "2020-11-10T01:37:18Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/47645/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/47645", 
      "id": 739496947, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/47645/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "MDU6SXNzdWU3Mzk0OTY5NDc=", 
      "number": 47645, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/47645/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/47645/timeline", 
      "title": "DISABLED test_broadcast_cuda (__main__.TestDistBackendWithFork)", 
      "updated_at": "2021-09-28T04:48:42Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/47645", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/2453524?v=4", 
        "events_url": "https://api.github.com/users/malfet/events{/privacy}", 
        "followers_url": "https://api.github.com/users/malfet/followers", 
        "following_url": "https://api.github.com/users/malfet/following{/other_user}", 
        "gists_url": "https://api.github.com/users/malfet/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/malfet", 
        "id": 2453524, 
        "login": "malfet", 
        "node_id": "MDQ6VXNlcjI0NTM1MjQ=", 
        "organizations_url": "https://api.github.com/users/malfet/orgs", 
        "received_events_url": "https://api.github.com/users/malfet/received_events", 
        "repos_url": "https://api.github.com/users/malfet/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/malfet/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/malfet/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/malfet"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/361522/workflows/0e36477a-ade5-4e87-a33b-49437af2531f/jobs/15247666/steps\r\n\r\n```\r\n======================================================================\r\nERROR [6.792s]: test_iterable_style_dataset (__main__.TestDataLoaderPersistentWorkers)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 990, in _try_get_data\r\n    data = self._data_queue.get(timeout=timeout)\r\n  File \"C:\\Jenkins\\Miniconda3\\lib\\multiprocessing\\queues.py\", line 108, in get\r\n    raise Empty\r\n_queue.Empty\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"test_dataloader.py\", line 1183, in test_iterable_style_dataset\r\n    self.assertNotWarn(lambda: next(it), \"Should not warn before accessing len(dataloader)\")\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\testing\\_internal\\common_utils.py\", line 1699, in assertNotWarn\r\n    callable()\r\n  File \"test_dataloader.py\", line 1183, in <lambda>\r\n    self.assertNotWarn(lambda: next(it), \"Should not warn before accessing len(dataloader)\")\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 521, in __next__\r\n    data = self._next_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1186, in _next_data\r\n    idx, data = self._get_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1152, in _get_data\r\n    success, data = self._try_get_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1003, in _try_get_data\r\n    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e\r\nRuntimeError: DataLoader worker (pid(s) 1928, 6440, 5856) exited unexpectedly\r\n\r\n----------------------------------------------------------------------\r\nRan 141 tests in 248.011s\r\n\r\nFAILED (errors=1, skipped=18)\r\n```\n\ncc @SsnL @VitalyFedyunin @ejguan", 
      "closed_at": null, 
      "comments": 0, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/62968/comments", 
      "created_at": "2021-08-09T15:32:27Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/62968/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/62968", 
      "id": 964118833, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.utils.data.DataLoader and Sampler", 
          "id": 1076923878, 
          "name": "module: dataloader", 
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/62968/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "MDU6SXNzdWU5NjQxMTg4MzM=", 
      "number": 62968, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/62968/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/62968/timeline", 
      "title": "DISABLED test_iterable_style_dataset (__main__.TestDataLoaderPersistentWorkers)", 
      "updated_at": "2021-08-10T17:39:42Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/62968", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/16999635?v=4", 
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mrshenli/followers", 
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mrshenli", 
        "id": 16999635, 
        "login": "mrshenli", 
        "node_id": "MDQ6VXNlcjE2OTk5NjM1", 
        "organizations_url": "https://api.github.com/users/mrshenli/orgs", 
        "received_events_url": "https://api.github.com/users/mrshenli/received_events", 
        "repos_url": "https://api.github.com/users/mrshenli/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mrshenli"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/361526/workflows/6cc20b4e-4487-4215-aabf-289aa3a9df23/jobs/15248178/steps\r\n\r\n```\r\n======================================================================\r\nERROR [6.321s]: test_worker_seed (__main__.TestDataLoaderPersistentWorkers)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 990, in _try_get_data\r\n    data = self._data_queue.get(timeout=timeout)\r\n  File \"C:\\Jenkins\\Miniconda3\\lib\\multiprocessing\\queues.py\", line 108, in get\r\n    raise Empty\r\n_queue.Empty\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"test_dataloader.py\", line 1332, in test_worker_seed\r\n    for batch in dataloader:\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 521, in __next__\r\n    data = self._next_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1186, in _next_data\r\n    idx, data = self._get_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1152, in _get_data\r\n    success, data = self._try_get_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1003, in _try_get_data\r\n    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e\r\nRuntimeError: DataLoader worker (pid(s) 2480) exited unexpectedly\r\n```\n\ncc @SsnL @VitalyFedyunin @ejguan", 
      "closed_at": null, 
      "comments": 0, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/62969/comments", 
      "created_at": "2021-08-09T15:34:16Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/62969/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/62969", 
      "id": 964120440, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.utils.data.DataLoader and Sampler", 
          "id": 1076923878, 
          "name": "module: dataloader", 
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/62969/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "MDU6SXNzdWU5NjQxMjA0NDA=", 
      "number": 62969, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/62969/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/62969/timeline", 
      "title": "DISABLED test_worker_seed (__main__.TestDataLoaderPersistentWorkers)", 
      "updated_at": "2021-08-10T17:39:34Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/62969", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/16999635?v=4", 
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mrshenli/followers", 
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mrshenli", 
        "id": 16999635, 
        "login": "mrshenli", 
        "node_id": "MDQ6VXNlcjE2OTk5NjM1", 
        "organizations_url": "https://api.github.com/users/mrshenli/orgs", 
        "received_events_url": "https://api.github.com/users/mrshenli/received_events", 
        "repos_url": "https://api.github.com/users/mrshenli/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mrshenli"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/361526/workflows/6cc20b4e-4487-4215-aabf-289aa3a9df23/jobs/15248178/steps\r\n\r\n```\r\n======================================================================\r\nERROR [6.479s]: test_worker_seed_reproducibility (__main__.TestDataLoaderPersistentWorkers)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 990, in _try_get_data\r\n    data = self._data_queue.get(timeout=timeout)\r\n  File \"C:\\Jenkins\\Miniconda3\\lib\\multiprocessing\\queues.py\", line 108, in get\r\n    raise Empty\r\n_queue.Empty\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"test_dataloader.py\", line 1343, in test_worker_seed_reproducibility\r\n    self.assertEqual(set(int(batch) for batch in get_dataloader()), set(int(batch) for batch in get_dataloader()))\r\n  File \"test_dataloader.py\", line 1343, in <genexpr>\r\n    self.assertEqual(set(int(batch) for batch in get_dataloader()), set(int(batch) for batch in get_dataloader()))\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 521, in __next__\r\n    data = self._next_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1186, in _next_data\r\n    idx, data = self._get_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1152, in _get_data\r\n    success, data = self._try_get_data()\r\n  File \"C:\\Users\\circleci\\project\\build\\win_tmp\\build\\torch\\utils\\data\\dataloader.py\", line 1003, in _try_get_data\r\n    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e\r\nRuntimeError: DataLoader worker (pid(s) 1936) exited unexpectedly\r\n```\n\ncc @SsnL @VitalyFedyunin @ejguan", 
      "closed_at": null, 
      "comments": 0, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/62970/comments", 
      "created_at": "2021-08-09T15:35:08Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/62970/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/62970", 
      "id": 964121193, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.utils.data.DataLoader and Sampler", 
          "id": 1076923878, 
          "name": "module: dataloader", 
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/62970/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "MDU6SXNzdWU5NjQxMjExOTM=", 
      "number": 62970, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/62970/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/62970/timeline", 
      "title": "DISABLED test_worker_seed_reproducibility (__main__.TestDataLoaderPersistentWorkers)", 
      "updated_at": "2021-08-10T17:39:49Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/62970", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/16999635?v=4", 
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mrshenli/followers", 
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mrshenli", 
        "id": 16999635, 
        "login": "mrshenli", 
        "node_id": "MDQ6VXNlcjE2OTk5NjM1", 
        "organizations_url": "https://api.github.com/users/mrshenli/orgs", 
        "received_events_url": "https://api.github.com/users/mrshenli/received_events", 
        "repos_url": "https://api.github.com/users/mrshenli/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mrshenli"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "See https://github.com/pytorch/pytorch/runs/3682832751. Relevant snippet:\r\n\r\n```\r\n======================================================================\r\nERROR [0.013s]: test_profiler (__main__.TestJit)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"test_jit.py\", line 2728, in test_profiler\r\n    traced_fn(x)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/autograd/profiler.py\", line 202, in __exit__\r\n    self.kineto_results = _disable_profiler()\r\nRuntimeError: cpu_trace->activities.size() == kineto_events_.size()INTERNAL ASSERT FAILED at \"/var/lib/jenkins/workspace/torch/csrc/autograd/profiler_kineto.cpp\":239, please report a bug to PyTorch. \r\n\r\n======================================================================\r\nERROR [0.017s]: test_always_alive_values (jit.test_freezing.TestMKLDNNReinplacing)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/var/lib/jenkins/workspace/test/jit/test_freezing.py\", line 2134, in test_always_alive_values\r\n    self.checkResults(mod_eager, mod)\r\n  File \"/var/lib/jenkins/workspace/test/jit/test_freezing.py\", line 2091, in checkResults\r\n    self.assertEqual(mod1(inp), mod2(inp))\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 1106, in _call_impl\r\n    return forward_call(*input, **kwargs)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 406, in prof_meth_call\r\n    return prof_callable(meth_call, *args, **kwargs)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 400, in prof_callable\r\n    return callable(*args, **kwargs)\r\nRuntimeError: Couldn't find method: '_conv_forward' on class: '__torch__.torch.nn.modules.conv.___torch_mangle_2152.Conv2d (of Python compilation unit at: 0x56250e1ebd80)'\r\n\r\n======================================================================\r\nERROR [0.010s]: test_merge_liveness (jit.test_freezing.TestMKLDNNReinplacing)\r\n----------------------------------------------------------------------\r\n  File \"test_jit.py\", line 5156, in test_cat\r\n    self.assertAutodiffNode(func2.graph_for(x, y), True, ['aten::cat'], [])\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py\", line 282, in assertAutodiffNode\r\n    found_all_nonfusible_nodes and found_all_fusible_nodes, err_msg)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1946, in assertEqual\r\n    super().assertTrue(x == y, msg=msg)\r\nAssertionError: False is not true : \r\nFailure in testing nodes' autodifferentiation. One or more nodes were expected to be autodiffed, but were not found in specified fusible/nonfusible DifferentiableGraph groups. \r\nSpecifically:\r\n  ['aten::cat'] were not in one of the DifferentiableGraphs when they were expected to be. Did you intend for these nodes to be autodiffed? If not, remove them from the list of nonfusible nodes.\r\n\r\n======================================================================\r\nFAIL [0.008s]: test_stack (__main__.TestScript)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"test_jit.py\", line 5198, in test_stack\r\n    self.assertAutodiffNode(func2.graph_for(x, y), True, ['aten::stack'], [])\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py\", line 282, in assertAutodiffNode\r\n    found_all_nonfusible_nodes and found_all_fusible_nodes, err_msg)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1946, in assertEqual\r\n    super().assertTrue(x == y, msg=msg)\r\nAssertionError: False is not true : \r\nFailure in testing nodes' autodifferentiation. One or more nodes were expected to be autodiffed, but were not found in specified fusible/nonfusible DifferentiableGraph groups. \r\nSpecifically:\r\n  ['aten::stack'] were not in one of the DifferentiableGraphs when they were expected to be. Did you intend for these nodes to be autodiffed? If not, remove them from the list of nonfusible nodes.\r\n\r\n======================================================================\r\nFAIL [0.004s]: test_tensor_requires_grad (__main__.TestScript)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"test_jit.py\", line 7165, in test_tensor_requires_grad\r\n    self.assertFalse(out_inp[2].requires_grad())\r\nAssertionError: True is not false\r\n\r\n======================================================================\r\nFAIL [0.004s]: test_size_and_sizes (jit.test_symbolic_shape_analysis.TestSymbolicShapeAnalysis)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/var/lib/jenkins/workspace/test/jit/test_symbolic_shape_analysis.py\", line 160, in test_size_and_sizes\r\n    self.assertEqual(next(graph.outputs()).type().symbolic_sizes(), [5, 8, sym1])\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1957, in assertEqual\r\n    super().assertEqual(x, y, msg=msg)\r\nAssertionError: None != [5, 8, -4896]\r\n\r\n======================================================================\r\nFAIL [0.007s]: test_canonicalize_tensor_iterator (jit.test_tracer.TestTracer)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/var/lib/jenkins/workspace/test/jit/test_tracer.py\", line 244, in test_canonicalize_tensor_iterator\r\n    self.assertTrue(str(traced.graph_for(x)).count(': int = prim::Constant') == 5)\r\nAssertionError: False is not true\r\n\r\n======================================================================\r\nFAIL [0.002s]: test_inplace_check (jit.test_tracer.TestTracer)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/var/lib/jenkins/workspace/test/jit/test_tracer.py\", line 342, in test_inplace_check\r\n    ge(x)\r\nAssertionError: RuntimeError not raised\r\n\r\n----------------------------------------------------------------------\r\nRan 2564 tests in 86.085s\r\n\r\nFAILED (failures=33, errors=16, skipped=91, expected failures=1)\r\n```\r\n\r\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git", 
      "closed_at": null, 
      "comments": 9, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/65521/comments", 
      "created_at": "2021-09-23T07:13:01Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/65521/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/65521", 
      "id": 1005089370, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "c5def5", 
          "default": false, 
          "description": "Add this issue/PR to JIT oncall triage queue", 
          "id": 679953983, 
          "name": "oncall: jit", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20jit"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Issues related to tests (not the torch.testing module)", 
          "id": 1300933336, 
          "name": "module: tests", 
          "node_id": "MDU6TGFiZWwxMzAwOTMzMzM2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tests"
        }, 
        {
          "color": "79C48B", 
          "default": false, 
          "description": "profiler-related issues (cpu, gpu, kineto)", 
          "id": 1883229970, 
          "name": "oncall: profiler", 
          "node_id": "MDU6TGFiZWwxODgzMjI5OTcw", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20profiler"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/65521/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z8476HJa", 
      "number": 65521, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/65521/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/65521/timeline", 
      "title": "DISABLED test_profiler (__main__.TestJit)", 
      "updated_at": "2021-10-05T20:53:52Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/65521", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Platforms: rocm\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport", 
      "closed_at": null, 
      "comments": 7, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/65884/comments", 
      "created_at": "2021-09-30T06:21:13Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/65884/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/65884", 
      "id": 1011764222, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/65884/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z848Tkv-", 
      "number": 65884, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/65884/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/65884/timeline", 
      "title": "DISABLED test_fn_grad_min_binary_cuda_float64 (__main__.TestGradientsCUDA)", 
      "updated_at": "2021-10-04T17:17:07Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/65884", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1617424?v=4", 
        "events_url": "https://api.github.com/users/suo/events{/privacy}", 
        "followers_url": "https://api.github.com/users/suo/followers", 
        "following_url": "https://api.github.com/users/suo/following{/other_user}", 
        "gists_url": "https://api.github.com/users/suo/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/suo", 
        "id": 1617424, 
        "login": "suo", 
        "node_id": "MDQ6VXNlcjE2MTc0MjQ=", 
        "organizations_url": "https://api.github.com/users/suo/orgs", 
        "received_events_url": "https://api.github.com/users/suo/received_events", 
        "repos_url": "https://api.github.com/users/suo/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/suo/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/suo/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/suo"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Flaky on CI, for example in this https://github.com/pytorch/pytorch/runs/3816958493?check_suite_focus=true.\r\n\r\nThis was on the 10.2 linux build.\r\n\r\nA better log view can be found by expanding on the linux 10.2 distributed tests here: https://hud.pytorch.org/commit/b8e19992533a2257f457926e6535f54054fc2003\r\n\r\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang", 
      "closed_at": null, 
      "comments": 4, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66207/comments", 
      "created_at": "2021-10-06T16:44:31Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66207/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66207", 
      "id": 1018734838, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }, 
        {
          "color": "5319E7", 
          "default": false, 
          "description": "Add this issue/PR to R2P (elastic) oncall triage queue", 
          "id": 3486427601, 
          "name": "oncall: r2p", 
          "node_id": "LA_kwDOA-j9z87PzqnR", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20r2p"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66207/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z848uKj2", 
      "number": 66207, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 1, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 1, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66207/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66207/timeline", 
      "title": "DISABLED test_create_store_single_server (__main__.DistributedUtilTest)", 
      "updated_at": "2021-11-02T19:48:18Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66207", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/31798555?v=4", 
        "events_url": "https://api.github.com/users/janeyx99/events{/privacy}", 
        "followers_url": "https://api.github.com/users/janeyx99/followers", 
        "following_url": "https://api.github.com/users/janeyx99/following{/other_user}", 
        "gists_url": "https://api.github.com/users/janeyx99/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/janeyx99", 
        "id": 31798555, 
        "login": "janeyx99", 
        "node_id": "MDQ6VXNlcjMxNzk4NTU1", 
        "organizations_url": "https://api.github.com/users/janeyx99/orgs", 
        "received_events_url": "https://api.github.com/users/janeyx99/received_events", 
        "repos_url": "https://api.github.com/users/janeyx99/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/janeyx99/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/janeyx99/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/janeyx99"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Remove the `check_batched_forward_grad=False` setting on the corresponding OpInfo to replicate:\r\n\r\n\r\n<details>\r\n<summary>\r\ntest_forward_mode_AD_{imag,real}_cpu_complex128 (conjugate view issue, need to investigate)\r\n</summary>\r\n\r\n```\r\n======================================================================\r\nERROR: test_forward_mode_AD_real_cpu_complex128 (__main__.TestGradientsCPU)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 376, in instantiated_test\r\n    raise rte\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 371, in instantiated_test\r\n    result = test(self, **param_kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 737, in test_wrapper\r\n    return test(*args, **kwargs)\r\n  File \"test/test_ops.py\", line 672, in test_forward_mode_AD\r\n    self._forward_grad_helper(device, dtype, op, op.get_op())\r\n  File \"test/test_ops.py\", line 656, in _forward_grad_helper\r\n    self._grad_test_helper(device, dtype, op, variant, check_forward_ad=True, check_backward_ad=False,\r\n  File \"test/test_ops.py\", line 587, in _grad_test_helper\r\n    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,\r\n  File \"test/test_ops.py\", line 559, in _check_helper\r\n    self.assertTrue(gradcheck(fn, gradcheck_args,\r\n  File \"/local/pytorch5/torch/testing/_internal/common_utils.py\", line 2689, in gradcheck\r\n    return torch.autograd.gradcheck(fn, inputs, **kwargs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 1332, in gradcheck\r\n    return _gradcheck_helper(**args)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 1351, in _gradcheck_helper\r\n    _test_batched_grad_forward_ad(func, tupled_inputs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 786, in _test_batched_grad_forward_ad\r\n    expected = [jvp(t) for t in tangents]\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 786, in <listcomp>\r\n    expected = [jvp(t) for t in tangents]\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 771, in jvp\r\n    dual_outputs = _as_tuple(func(*inputs_with_dual))\r\n  File \"test/test_ops.py\", line 547, in fn\r\n    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_methods_invocations.py\", line 504, in <lambda>\r\n    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck\r\nRuntimeError: view_as_real doesn't work on unresolved conjugated tensors.  To resolve the conjugate tensor so you can view it as real, use self.resolve_conj(); however, be warned that the resulting tensor will NOT alias the original.\r\n```\r\n\r\n</details>\r\n\r\n<details>\r\n<summary>\r\ntest_forward_mode_AD_lu_solve_cpu_{float64,complex128} (need to investigate)\r\n</summary>\r\n\r\n```\r\n======================================================================\r\nERROR: test_forward_mode_AD_lu_solve_cpu_float64 (__main__.TestGradientsCPU)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 790, in _test_batched_grad_forward_ad\r\n    result = _vmap(jvp)(torch.stack(tangents))\r\n  File \"/local/pytorch5/torch/_vmap_internals.py\", line 271, in wrapped\r\n    batched_outputs = func(*batched_inputs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 771, in jvp\r\n    dual_outputs = _as_tuple(func(*inputs_with_dual))\r\n  File \"test/test_ops.py\", line 547, in fn\r\n    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_methods_invocations.py\", line 504, in <lambda>\r\n    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck\r\nRuntimeError: vmap: Calling Tensor.as_strided is not supported unless the batch dims being vmapped over are at the front of the tensor (in memory layout). When they are not at the front of the tensor this operation can be error prone so we actively discourage it; please file us a bug report and/or try to express the as_strided operation in terms of PyTorch view operations\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 376, in instantiated_test\r\n    raise rte\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 371, in instantiated_test\r\n    result = test(self, **param_kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 772, in dep_fn\r\n    return fn(slf, *args, **kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 772, in dep_fn\r\n    return fn(slf, *args, **kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 772, in dep_fn\r\n    return fn(slf, *args, **kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 737, in test_wrapper\r\n    return test(*args, **kwargs)\r\n  File \"test/test_ops.py\", line 672, in test_forward_mode_AD\r\n    self._forward_grad_helper(device, dtype, op, op.get_op())\r\n  File \"test/test_ops.py\", line 656, in _forward_grad_helper\r\n    self._grad_test_helper(device, dtype, op, variant, check_forward_ad=True, check_backward_ad=False,\r\n  File \"test/test_ops.py\", line 587, in _grad_test_helper\r\n    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,\r\n  File \"test/test_ops.py\", line 559, in _check_helper\r\n    self.assertTrue(gradcheck(fn, gradcheck_args,\r\n  File \"/local/pytorch5/torch/testing/_internal/common_utils.py\", line 2689, in gradcheck\r\n    return torch.autograd.gradcheck(fn, inputs, **kwargs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 1332, in gradcheck\r\n    return _gradcheck_helper(**args)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 1351, in _gradcheck_helper\r\n    _test_batched_grad_forward_ad(func, tupled_inputs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 793, in _test_batched_grad_forward_ad\r\n    raise GradcheckError(\r\ntorch.autograd.gradcheck.GradcheckError: While computing batched gradients, got: vmap: Calling Tensor.as_strided is not supported unless the batch dims being vmapped over are at the front of the tensor (in memory layout). When they are not at the front of the tensor this operation can be error prone so we actively discourage it; please file us a bug report and/or try to express the as_strided operation in terms of PyTorch view operations\r\n\r\n\r\ngradcheck failed while testing batched gradient computation with forward-mode AD.\r\nThis test is enabled automatically when both `check_batched_grad=True`\r\nand `check_forward_ad=True`, but can be disabled in the following ways\r\ndependong on how the test was invoked (via a test that calls gradcheck\r\ndirectly or via an autogenerated test).\r\n\r\nIf you are adding a new operator, please file an issue and then use one of the\r\nworkarounds. The workaround depends on how your test invokes gradcheck/gradgradcheck.\r\nIf the test\r\n- manually invokes gradcheck/gradgradcheck, then call gradcheck/gradgradcheck\r\n  with `check_batched_forward_grad=False` as a keyword argument.\r\n- is OpInfo-based (e.g., in test_ops.py), then modify the OpInfo for the test\r\n  to have `check_batched_forward_grad=False`\r\n```\r\n\r\n</details>\r\n\r\n<details>\r\n<summary>\r\ntest_forward_mode_AD_unfold_cpu_{float64,complex128} (could be an issue with scalar inputs)\r\n</summary>\r\n\r\n```\r\n======================================================================\r\nERROR: test_forward_mode_AD_unfold_cpu_float64 (__main__.TestGradientsCPU)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File /local/pytorch5/torch/testing/_internal/common_device_type.py\", line 371, in instantiated_test\r\n    result = test(self, **param_kwargs)\r\n  File /local/pytorch5/torch/testing/_internal/common_device_type.py\", line 737, in test_wrapper\r\n    return test(*args, **kwargs)\r\n  File \"test/test_ops.py\", line 672, in test_forward_mode_AD\r\n    self._forward_grad_helper(device, dtype, op, op.get_op())\r\n  File \"test/test_ops.py\", line 656, in _forward_grad_helper\r\n    self._grad_test_helper(device, dtype, op, variant, check_forward_ad=True, check_backward_ad=False,\r\n  File \"test/test_ops.py\", line 587, in _grad_test_helper\r\n    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,\r\n  File \"test/test_ops.py\", line 559, in _check_helper\r\n    self.assertTrue(gradcheck(fn, gradcheck_args,\r\n  File /local/pytorch5/torch/testing/_internal/common_utils.py\", line 2689, in gradcheck\r\n    return torch.autograd.gradcheck(fn, inputs, **kwargs)\r\n  File /local/pytorch5/torch/autograd/gradcheck.py\", line 1332, in gradcheck\r\n    return _gradcheck_helper(**args)\r\n  File /local/pytorch5/torch/autograd/gradcheck.py\", line 1351, in _gradcheck_helper\r\n    _test_batched_grad_forward_ad(func, tupled_inputs)\r\n  File /local/pytorch5/torch/autograd/gradcheck.py\", line 790, in _test_batched_grad_forward_ad\r\n    result = _vmap(jvp)(torch.stack(tangents))\r\n  File /local/pytorch5/torch/_vmap_internals.py\", line 271, in wrapped\r\n    batched_outputs = func(*batched_inputs)\r\n  File /local/pytorch5/torch/autograd/gradcheck.py\", line 771, in jvp\r\n    dual_outputs = _as_tuple(func(*inputs_with_dual))\r\n  File \"test/test_ops.py\", line 547, in fn\r\n    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)\r\n  File /local/pytorch5/torch/testing/_internal/common_methods_invocations.py\", line 504, in <lambda>\r\n    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck\r\n  File /local/pytorch5/torch/testing/_internal/common_methods_invocations.py\", line 9427, in <lambda>\r\n    op=lambda x, *args: x.unfold(*args),\r\nIndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)\r\n\r\n```\r\n\r\n</details>\r\n\r\n- test_forward_mode_AD_linalg_eigh_cpu_float64` (stack not implemented for forward AD)\r\n<details>\r\n<summary>\r\ntest_forward_mode_AD_nn_functional_linear_cpu_{float64,complex128} (could be a precision issue?)\r\n</summary>\r\n\r\n```\r\nGot:\r\ntensor([[[-2.2989+0.5745j,  3.0938-1.1124j,  2.1925-3.4686j, -1.6909-0.0380j]],\r\n\r\n        [[-1.0700-1.3572j,  0.7086+5.1560j,  3.3267+3.1176j,  0.1303+0.4241j]]],\r\n       grad_fn=<CopySlices>)\r\n\r\nExpected:\r\ntensor([[-2.2989+0.5745j,  3.0938-1.1124j,  2.1925-3.4686j, -1.6909-0.0380j],\r\n        [-1.0700-1.3572j,  0.7086+5.1560j,  3.3267+3.1176j,  0.1303+0.4241j]],\r\n       grad_fn=<StackBackward0>)\r\n```\r\n\r\n</details>\r\n\r\n<details>\r\n<summary>\r\ntest_forward_mode_AD_einsum_cpu_complex128\r\n</summary>\r\n\r\n```\r\n======================================================================\r\nERROR: test_forward_mode_AD_einsum_cpu_complex128 (__main__.TestGradientsCPU)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 376, in instantiated_test\r\n    raise rte\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 371, in instantiated_test\r\n    result = test(self, **param_kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_device_type.py\", line 737, in test_wrapper\r\n    return test(*args, **kwargs)\r\n  File \"test/test_ops.py\", line 675, in test_forward_mode_AD\r\n    self._forward_grad_helper(device, dtype, op, op.get_op())\r\n  File \"test/test_ops.py\", line 657, in _forward_grad_helper\r\n    self._grad_test_helper(device, dtype, op, variant, check_forward_ad=True, check_backward_ad=False,\r\n  File \"test/test_ops.py\", line 587, in _grad_test_helper\r\n    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,\r\n  File \"test/test_ops.py\", line 559, in _check_helper\r\n    self.assertTrue(gradcheck(fn, gradcheck_args,\r\n  File \"/local/pytorch5/torch/testing/_internal/common_utils.py\", line 2718, in gradcheck\r\n    return torch.autograd.gradcheck(fn, inputs, **kwargs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 1329, in gradcheck\r\n    return _gradcheck_helper(**args)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 1348, in _gradcheck_helper\r\n    _test_batched_grad_forward_ad(func, tupled_inputs)\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 782, in _test_batched_grad_forward_ad\r\n    expected = [jvp(t) for t in tangents]\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 782, in <listcomp>\r\n    expected = [jvp(t) for t in tangents]\r\n  File \"/local/pytorch5/torch/autograd/gradcheck.py\", line 767, in jvp\r\n    dual_outputs = _as_tuple(func(*inputs_with_dual))\r\n  File \"test/test_ops.py\", line 547, in fn\r\n    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)\r\n  File \"/local/pytorch5/torch/testing/_internal/common_methods_invocations.py\", line 504, in <lambda>\r\n    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck\r\n  File \"/local/pytorch5/torch/testing/_internal/common_methods_invocations.py\", line 9905, in <lambda>\r\n    op=lambda tensors, equation: torch.einsum(equation, tensors),\r\n  File \"/local/pytorch5/torch/functional.py\", line 328, in einsum\r\n    return einsum(equation, *_operands)\r\n  File \"/local/pytorch5/torch/functional.py\", line 330, in einsum\r\n    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]\r\nRuntimeError: !this_view_meta->has_fw_view()INTERNAL ASSERT FAILED at \"../torch/csrc/autograd/autograd_meta.cpp\":171, please report a bug to PyTorch. Expected the output of forward differentiable view operations to have the tangent have the same layout as primal\r\n```\r\n\r\n</details>\r\n\r\n<details>\r\n<summary>\r\ntest_forward_mode_AD_linalg_eigvalsh_cpu_float64\r\n</summary>\r\n\r\n```\r\n ======================================================================\r\nERROR [0.010s]: test_forward_mode_AD_linalg_eigvalsh_cpu_float64 (__main__.TestGradientsCPU)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py\", line 786, in _test_batched_grad_forward_ad\r\n    result = _vmap(jvp)(torch.stack(tangents))\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/_vmap_internals.py\", line 271, in wrapped\r\n    batched_outputs = func(*batched_inputs)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py\", line 767, in jvp\r\n    dual_outputs = _as_tuple(func(*inputs_with_dual))\r\n  File \"test_ops.py\", line 608, in fn\r\n    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_methods_invocations.py\", line 7098, in gradcheck_wrapper_hermitian_input\r\n    return op(input + input.mH, *args, **kwargs)\r\nRuntimeError: vmap: Calling Tensor.as_strided is not supported unless the batch dims being vmapped over are at the front of the tensor (in memory layout). When they are not at the front of the tensor this operation can be error prone so we actively discourage it; please file us a bug report and/or try to express the as_strided operation in terms of PyTorch view operations\r\n\r\n```\r\n\r\n</details>\r\n\r\ncc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry", 
      "closed_at": null, 
      "comments": 0, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66357/comments", 
      "created_at": "2021-10-09T02:25:49Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66357/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66357", 
      "id": 1021573996, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.autograd, and the autograd engine in general", 
          "id": 1076922545, 
          "name": "module: autograd", 
          "node_id": "MDU6TGFiZWwxMDc2OTIyNTQ1", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20autograd"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Issues related to tests (not the torch.testing module)", 
          "id": 1300933336, 
          "name": "module: tests", 
          "node_id": "MDU6TGFiZWwxMzAwOTMzMzM2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tests"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66357/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z8484_ts", 
      "number": 66357, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66357/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66357/timeline", 
      "title": "OpInfos disabled for batched forward grad computation", 
      "updated_at": "2021-11-10T15:32:56Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66357", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/13428986?v=4", 
        "events_url": "https://api.github.com/users/soulitzer/events{/privacy}", 
        "followers_url": "https://api.github.com/users/soulitzer/followers", 
        "following_url": "https://api.github.com/users/soulitzer/following{/other_user}", 
        "gists_url": "https://api.github.com/users/soulitzer/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/soulitzer", 
        "id": 13428986, 
        "login": "soulitzer", 
        "node_id": "MDQ6VXNlcjEzNDI4OTg2", 
        "organizations_url": "https://api.github.com/users/soulitzer/orgs", 
        "received_events_url": "https://api.github.com/users/soulitzer/received_events", 
        "repos_url": "https://api.github.com/users/soulitzer/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/soulitzer/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/soulitzer/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/soulitzer"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/13089297?v=4", 
        "events_url": "https://api.github.com/users/robieta/events{/privacy}", 
        "followers_url": "https://api.github.com/users/robieta/followers", 
        "following_url": "https://api.github.com/users/robieta/following{/other_user}", 
        "gists_url": "https://api.github.com/users/robieta/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/robieta", 
        "id": 13089297, 
        "login": "robieta", 
        "node_id": "MDQ6VXNlcjEzMDg5Mjk3", 
        "organizations_url": "https://api.github.com/users/robieta/orgs", 
        "received_events_url": "https://api.github.com/users/robieta/received_events", 
        "repos_url": "https://api.github.com/users/robieta/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/robieta/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/robieta/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/robieta"
      }, 
      "assignees": [
        {
          "avatar_url": "https://avatars.githubusercontent.com/u/13089297?v=4", 
          "events_url": "https://api.github.com/users/robieta/events{/privacy}", 
          "followers_url": "https://api.github.com/users/robieta/followers", 
          "following_url": "https://api.github.com/users/robieta/following{/other_user}", 
          "gists_url": "https://api.github.com/users/robieta/gists{/gist_id}", 
          "gravatar_id": "", 
          "html_url": "https://github.com/robieta", 
          "id": 13089297, 
          "login": "robieta", 
          "node_id": "MDQ6VXNlcjEzMDg5Mjk3", 
          "organizations_url": "https://api.github.com/users/robieta/orgs", 
          "received_events_url": "https://api.github.com/users/robieta/received_events", 
          "repos_url": "https://api.github.com/users/robieta/repos", 
          "site_admin": false, 
          "starred_url": "https://api.github.com/users/robieta/starred{/owner}{/repo}", 
          "subscriptions_url": "https://api.github.com/users/robieta/subscriptions", 
          "type": "User", 
          "url": "https://api.github.com/users/robieta"
        }
      ], 
      "author_association": "CONTRIBUTOR", 
      "body": "See https://github.com/pytorch/pytorch/runs/3872033982, relevant snippet:\r\n\r\n```\r\n  test_timer_tiny_fast_snippet (__main__.TestBenchmarkUtils) ... ERROR (21.201s)\r\n\r\n======================================================================\r\nERROR [21.201s]: test_timer_tiny_fast_snippet (__main__.TestBenchmarkUtils)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 981, in wrapper\r\n    fn(*args, **kwargs)\r\n  File \"benchmark_utils/test_benchmark_utils.py\", line 177, in test_timer_tiny_fast_snippet\r\n    median = timer.blocked_autorange().median\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/utils/benchmark/utils/timer.py\", line 389, in blocked_autorange\r\n    number = self._estimate_block_size(min_run_time)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/utils/benchmark/utils/timer.py\", line 307, in _estimate_block_size\r\n    relative_overhead = overhead / time_taken\r\nZeroDivisionError: float division by zero\r\n\r\n----------------------------------------------------------------------\r\nRan 9 tests in 409.563s\r\n\r\nFAILED (errors=1, skipped=5)\r\n```\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry", 
      "closed_at": null, 
      "comments": 4, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66503/comments", 
      "created_at": "2021-10-12T20:17:30Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66503/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66503", 
      "id": 1024306649, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Issues related to tests (not the torch.testing module)", 
          "id": 1300933336, 
          "name": "module: tests", 
          "node_id": "MDU6TGFiZWwxMzAwOTMzMzM2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tests"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "E83C95", 
          "default": false, 
          "description": "related to torch.utils.benchmark e.g. Timer", 
          "id": 3307971793, 
          "name": "module: benchmark", 
          "node_id": "MDU6TGFiZWwzMzA3OTcxNzkz", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20benchmark"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66503/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849Da3Z", 
      "number": 66503, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66503/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66503/timeline", 
      "title": "DISABLED test_timer_tiny_fast_snippet (__main__.TestBenchmarkUtils)", 
      "updated_at": "2021-10-18T15:46:22Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66503", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Appears to be failing again after re-enabling onnx tests, going to disable for now so we can re-introduce onnx tests\r\n\r\nRe-enabling onnx tests: \r\n* https://github.com/pytorch/pytorch/pull/66513\r\n\r\nPrevious related issues:\r\n* https://github.com/pytorch/pytorch/issues/63968\r\n* https://github.com/pytorch/pytorch/issues/34658\r\n\r\ncc @BowenBao @neginraoof", 
      "closed_at": null, 
      "comments": 3, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66528/comments", 
      "created_at": "2021-10-12T23:58:35Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66528/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66528", 
      "id": 1024612461, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.onnx", 
          "id": 693805995, 
          "name": "module: onnx", 
          "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20onnx"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "bfdadc", 
          "default": false, 
          "description": "Denotes a (flaky) test currently skipped in CI.", 
          "id": 1679533716, 
          "name": "skipped", 
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66528/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849Elht", 
      "number": 66528, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66528/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66528/timeline", 
      "title": "DISABLED test_keypoint_rcnn (__main__.TestONNXRuntime_opset11)", 
      "updated_at": "2021-10-15T20:41:31Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66528", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1700823?v=4", 
        "events_url": "https://api.github.com/users/seemethere/events{/privacy}", 
        "followers_url": "https://api.github.com/users/seemethere/followers", 
        "following_url": "https://api.github.com/users/seemethere/following{/other_user}", 
        "gists_url": "https://api.github.com/users/seemethere/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/seemethere", 
        "id": 1700823, 
        "login": "seemethere", 
        "node_id": "MDQ6VXNlcjE3MDA4MjM=", 
        "organizations_url": "https://api.github.com/users/seemethere/orgs", 
        "received_events_url": "https://api.github.com/users/seemethere/received_events", 
        "repos_url": "https://api.github.com/users/seemethere/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/seemethere/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/seemethere/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/seemethere"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/68879799?v=4", 
        "events_url": "https://api.github.com/users/ejguan/events{/privacy}", 
        "followers_url": "https://api.github.com/users/ejguan/followers", 
        "following_url": "https://api.github.com/users/ejguan/following{/other_user}", 
        "gists_url": "https://api.github.com/users/ejguan/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/ejguan", 
        "id": 68879799, 
        "login": "ejguan", 
        "node_id": "MDQ6VXNlcjY4ODc5Nzk5", 
        "organizations_url": "https://api.github.com/users/ejguan/orgs", 
        "received_events_url": "https://api.github.com/users/ejguan/received_events", 
        "repos_url": "https://api.github.com/users/ejguan/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/ejguan/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/ejguan/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/ejguan"
      }, 
      "assignees": [
        {
          "avatar_url": "https://avatars.githubusercontent.com/u/68879799?v=4", 
          "events_url": "https://api.github.com/users/ejguan/events{/privacy}", 
          "followers_url": "https://api.github.com/users/ejguan/followers", 
          "following_url": "https://api.github.com/users/ejguan/following{/other_user}", 
          "gists_url": "https://api.github.com/users/ejguan/gists{/gist_id}", 
          "gravatar_id": "", 
          "html_url": "https://github.com/ejguan", 
          "id": 68879799, 
          "login": "ejguan", 
          "node_id": "MDQ6VXNlcjY4ODc5Nzk5", 
          "organizations_url": "https://api.github.com/users/ejguan/orgs", 
          "received_events_url": "https://api.github.com/users/ejguan/received_events", 
          "repos_url": "https://api.github.com/users/ejguan/repos", 
          "site_admin": false, 
          "starred_url": "https://api.github.com/users/ejguan/starred{/owner}{/repo}", 
          "subscriptions_url": "https://api.github.com/users/ejguan/subscriptions", 
          "type": "User", 
          "url": "https://api.github.com/users/ejguan"
        }
      ], 
      "author_association": "MEMBER", 
      "body": "This test fails nondeterministically on master. Here are all the failures in the last 30 days: https://fburl.com/scuba/opensource_ci_jobs/wa4res83\r\n\r\nThere are only two, so it may be appropriate to do a retry or something for this test. Nevertheless, I am disabling for now while we decide what to do it.\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @SsnL @VitalyFedyunin @ejguan @NivekT", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66635/comments", 
      "created_at": "2021-10-14T17:41:09Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66635/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66635", 
      "id": 1026657439, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.utils.data.DataLoader and Sampler", 
          "id": 1076923878, 
          "name": "module: dataloader", 
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66635/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849MYyf", 
      "number": 66635, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 1, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 1, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66635/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66635/timeline", 
      "title": "DISABLED test_timeout (__main__.TestDataLoader)", 
      "updated_at": "2021-10-14T17:50:00Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66635", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1617424?v=4", 
        "events_url": "https://api.github.com/users/suo/events{/privacy}", 
        "followers_url": "https://api.github.com/users/suo/followers", 
        "following_url": "https://api.github.com/users/suo/following{/other_user}", 
        "gists_url": "https://api.github.com/users/suo/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/suo", 
        "id": 1617424, 
        "login": "suo", 
        "node_id": "MDQ6VXNlcjE2MTc0MjQ=", 
        "organizations_url": "https://api.github.com/users/suo/orgs", 
        "received_events_url": "https://api.github.com/users/suo/received_events", 
        "repos_url": "https://api.github.com/users/suo/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/suo/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/suo/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/suo"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Relevant snippet from https://github.com/pytorch/pytorch/runs/3942697773 : \r\n\r\n```\r\n======================================================================\r\nFAIL [0.005s]: test_profiler_seq_nr (__main__.TestAutograd)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/var/lib/jenkins/workspace/test/test_autograd.py\", line 2948, in test_profiler_seq_nr\r\n    self.assertFalse(found_sum)\r\nAssertionError: True is not false\r\n```\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git", 
      "closed_at": null, 
      "comments": 3, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66893/comments", 
      "created_at": "2021-10-19T20:12:15Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66893/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66893", 
      "id": 1030701202, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.autograd, and the autograd engine in general", 
          "id": 1076922545, 
          "name": "module: autograd", 
          "node_id": "MDU6TGFiZWwxMDc2OTIyNTQ1", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20autograd"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Issues related to tests (not the torch.testing module)", 
          "id": 1300933336, 
          "name": "module: tests", 
          "node_id": "MDU6TGFiZWwxMzAwOTMzMzM2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tests"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }, 
        {
          "color": "79C48B", 
          "default": false, 
          "description": "profiler-related issues (cpu, gpu, kineto)", 
          "id": 1883229970, 
          "name": "oncall: profiler", 
          "node_id": "MDU6TGFiZWwxODgzMjI5OTcw", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20profiler"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66893/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849b0CS", 
      "number": 66893, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66893/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66893/timeline", 
      "title": "DISABLED test_profiler_seq_nr (__main__.TestAutograd)", 
      "updated_at": "2021-10-25T17:14:22Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66893", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Found flaky on CI:\r\nhttps://github.com/pytorch/pytorch/runs/3954816134?check_suite_focus=true\r\n\r\n```\r\n======================================================================\r\nERROR [105.069s]: test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 424, in wrapper\r\n    self._join_processes(fn)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 643, in _join_processes\r\n    self._check_return_codes(elapsed_time)\r\n  File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 695, in _check_return_codes\r\n    i, elapsed_time\r\nRuntimeError: Process 0 terminated or timed out after 105.05612325668335 seconds\r\n```\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang", 
      "closed_at": null, 
      "comments": 3, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66951/comments", 
      "created_at": "2021-10-20T18:13:32Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66951/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66951", 
      "id": 1031693921, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66951/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849fmZh", 
      "number": 66951, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 1, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 1, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66951/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66951/timeline", 
      "title": "DISABLED test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)", 
      "updated_at": "2021-11-01T15:02:23Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66951", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/31798555?v=4", 
        "events_url": "https://api.github.com/users/janeyx99/events{/privacy}", 
        "followers_url": "https://api.github.com/users/janeyx99/followers", 
        "following_url": "https://api.github.com/users/janeyx99/following{/other_user}", 
        "gists_url": "https://api.github.com/users/janeyx99/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/janeyx99", 
        "id": 31798555, 
        "login": "janeyx99", 
        "node_id": "MDQ6VXNlcjMxNzk4NTU1", 
        "organizations_url": "https://api.github.com/users/janeyx99/orgs", 
        "received_events_url": "https://api.github.com/users/janeyx99/received_events", 
        "repos_url": "https://api.github.com/users/janeyx99/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/janeyx99/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/janeyx99/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/janeyx99"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Example flaky failure on trunk https://github.com/pytorch/pytorch/runs/3958042374\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/66982/comments", 
      "created_at": "2021-10-21T00:13:56Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/66982/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/66982", 
      "id": 1031930172, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/66982/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849ggE8", 
      "number": 66982, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/66982/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/66982/timeline", 
      "title": "DISABLED test_barrier_timeout_global (__main__.TestDistBackendWithSpawn", 
      "updated_at": "2021-10-21T00:14:18Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/66982", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1617424?v=4", 
        "events_url": "https://api.github.com/users/suo/events{/privacy}", 
        "followers_url": "https://api.github.com/users/suo/followers", 
        "following_url": "https://api.github.com/users/suo/following{/other_user}", 
        "gists_url": "https://api.github.com/users/suo/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/suo", 
        "id": 1617424, 
        "login": "suo", 
        "node_id": "MDQ6VXNlcjE2MTc0MjQ=", 
        "organizations_url": "https://api.github.com/users/suo/orgs", 
        "received_events_url": "https://api.github.com/users/suo/received_events", 
        "repos_url": "https://api.github.com/users/suo/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/suo/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/suo/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/suo"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Flaky failures in the last week: https://fburl.com/scuba/opensource_ci_jobs/inmj698k. They only appear to be on windows\r\n\r\nPlatforms: windows\n\ncc @peterjc123 @mszhanyi @skyline75489 @nbcsm", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67002/comments", 
      "created_at": "2021-10-21T06:15:35Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67002/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67002", 
      "id": 1032101348, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Windows support for PyTorch", 
          "id": 790080431, 
          "name": "module: windows", 
          "node_id": "MDU6TGFiZWw3OTAwODA0MzE=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20windows"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67002/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849hJ3k", 
      "number": 67002, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67002/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67002/timeline", 
      "title": "DISABLED test_fs_sharing (__main__.TestMultiprocessing)", 
      "updated_at": "2021-10-21T14:11:50Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67002", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1617424?v=4", 
        "events_url": "https://api.github.com/users/suo/events{/privacy}", 
        "followers_url": "https://api.github.com/users/suo/followers", 
        "following_url": "https://api.github.com/users/suo/following{/other_user}", 
        "gists_url": "https://api.github.com/users/suo/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/suo", 
        "id": 1617424, 
        "login": "suo", 
        "node_id": "MDQ6VXNlcjE2MTc0MjQ=", 
        "organizations_url": "https://api.github.com/users/suo/orgs", 
        "received_events_url": "https://api.github.com/users/suo/received_events", 
        "repos_url": "https://api.github.com/users/suo/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/suo/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/suo/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/suo"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Platforms: rocm, linux\r\n\r\nExample failures:\r\n- https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1427//console\r\n- https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1405//console\r\n- https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1378//console\r\n\r\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 3, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67101/comments", 
      "created_at": "2021-10-22T16:59:29Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67101/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67101", 
      "id": 1033783510, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }, 
        {
          "color": "bfdadc", 
          "default": false, 
          "description": "Denotes a (flaky) test currently skipped in CI.", 
          "id": 1679533716, 
          "name": "skipped", 
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67101/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849nkjW", 
      "number": 67101, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67101/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67101/timeline", 
      "title": "DISABLED test_nccl_timeout (__main__.NcclErrorHandlingTest)", 
      "updated_at": "2021-10-29T15:52:10Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67101", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1617424?v=4", 
        "events_url": "https://api.github.com/users/suo/events{/privacy}", 
        "followers_url": "https://api.github.com/users/suo/followers", 
        "following_url": "https://api.github.com/users/suo/following{/other_user}", 
        "gists_url": "https://api.github.com/users/suo/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/suo", 
        "id": 1617424, 
        "login": "suo", 
        "node_id": "MDQ6VXNlcjE2MTc0MjQ=", 
        "organizations_url": "https://api.github.com/users/suo/orgs", 
        "received_events_url": "https://api.github.com/users/suo/received_events", 
        "repos_url": "https://api.github.com/users/suo/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/suo/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/suo/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/suo"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Timing out when attempting to migrate linux gpu workflows to linux.4xlarge.nvidia.gpu\r\n\r\nhttps://github.com/pytorch/pytorch/pull/67264\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang", 
      "closed_at": null, 
      "comments": 2, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67287/comments", 
      "created_at": "2021-10-26T21:49:51Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67287/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67287", 
      "id": 1036771604, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67287/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849y-EU", 
      "number": 67287, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67287/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67287/timeline", 
      "title": "DISABLED test_add_param_group (__main__.TestZeroRedundancyOptimizerDistributed)", 
      "updated_at": "2021-10-27T03:23:10Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67287", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1700823?v=4", 
        "events_url": "https://api.github.com/users/seemethere/events{/privacy}", 
        "followers_url": "https://api.github.com/users/seemethere/followers", 
        "following_url": "https://api.github.com/users/seemethere/following{/other_user}", 
        "gists_url": "https://api.github.com/users/seemethere/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/seemethere", 
        "id": 1700823, 
        "login": "seemethere", 
        "node_id": "MDQ6VXNlcjE3MDA4MjM=", 
        "organizations_url": "https://api.github.com/users/seemethere/orgs", 
        "received_events_url": "https://api.github.com/users/seemethere/received_events", 
        "repos_url": "https://api.github.com/users/seemethere/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/seemethere/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/seemethere/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/seemethere"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "MEMBER", 
      "body": "Timing out when attempting to migrate to linux.4xlarge.nvidia.gpu\r\n\r\nSee https://github.com/pytorch/pytorch/pull/67264\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67289/comments", 
      "created_at": "2021-10-26T21:54:39Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67289/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67289", 
      "id": 1036774331, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67289/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849y-u7", 
      "number": 67289, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67289/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67289/timeline", 
      "title": "DISABLED test_zero_redundancy_optimizer (__main__.TestZeroRedundancyOptimizerDistributed)", 
      "updated_at": "2021-10-26T22:10:51Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67289", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1700823?v=4", 
        "events_url": "https://api.github.com/users/seemethere/events{/privacy}", 
        "followers_url": "https://api.github.com/users/seemethere/followers", 
        "following_url": "https://api.github.com/users/seemethere/following{/other_user}", 
        "gists_url": "https://api.github.com/users/seemethere/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/seemethere", 
        "id": 1700823, 
        "login": "seemethere", 
        "node_id": "MDQ6VXNlcjE3MDA4MjM=", 
        "organizations_url": "https://api.github.com/users/seemethere/orgs", 
        "received_events_url": "https://api.github.com/users/seemethere/received_events", 
        "repos_url": "https://api.github.com/users/seemethere/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/seemethere/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/seemethere/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/seemethere"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/16999635?v=4", 
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mrshenli/followers", 
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mrshenli", 
        "id": 16999635, 
        "login": "mrshenli", 
        "node_id": "MDQ6VXNlcjE2OTk5NjM1", 
        "organizations_url": "https://api.github.com/users/mrshenli/orgs", 
        "received_events_url": "https://api.github.com/users/mrshenli/received_events", 
        "repos_url": "https://api.github.com/users/mrshenli/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mrshenli"
      }, 
      "assignees": [
        {
          "avatar_url": "https://avatars.githubusercontent.com/u/16999635?v=4", 
          "events_url": "https://api.github.com/users/mrshenli/events{/privacy}", 
          "followers_url": "https://api.github.com/users/mrshenli/followers", 
          "following_url": "https://api.github.com/users/mrshenli/following{/other_user}", 
          "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}", 
          "gravatar_id": "", 
          "html_url": "https://github.com/mrshenli", 
          "id": 16999635, 
          "login": "mrshenli", 
          "node_id": "MDQ6VXNlcjE2OTk5NjM1", 
          "organizations_url": "https://api.github.com/users/mrshenli/orgs", 
          "received_events_url": "https://api.github.com/users/mrshenli/received_events", 
          "repos_url": "https://api.github.com/users/mrshenli/repos", 
          "site_admin": false, 
          "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}", 
          "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions", 
          "type": "User", 
          "url": "https://api.github.com/users/mrshenli"
        }
      ], 
      "author_association": "MEMBER", 
      "body": "Discovered a timeout when moving linux gpu workflows to g3.4xlarge machines https://github.com/pytorch/pytorch/pull/67264\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67295/comments", 
      "created_at": "2021-10-26T22:51:27Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67295/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67295", 
      "id": 1036806759, 
      "labels": [
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67295/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z849zGpn", 
      "number": 67295, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67295/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67295/timeline", 
      "title": "DISABLED test_sharding (__main__.TestZeroRedundancyOptimizerDistributed)", 
      "updated_at": "2021-11-03T18:42:18Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67295", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1700823?v=4", 
        "events_url": "https://api.github.com/users/seemethere/events{/privacy}", 
        "followers_url": "https://api.github.com/users/seemethere/followers", 
        "following_url": "https://api.github.com/users/seemethere/following{/other_user}", 
        "gists_url": "https://api.github.com/users/seemethere/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/seemethere", 
        "id": 1700823, 
        "login": "seemethere", 
        "node_id": "MDQ6VXNlcjE3MDA4MjM=", 
        "organizations_url": "https://api.github.com/users/seemethere/orgs", 
        "received_events_url": "https://api.github.com/users/seemethere/received_events", 
        "repos_url": "https://api.github.com/users/seemethere/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/seemethere/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/seemethere/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/seemethere"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "### \ud83d\udc1b Describe the bug\n\nFor a flaky failure example, see https://hud.pytorch.org/commit/pytorch/pytorch/62feadd76fb5760faccd526d9064b9ba5de13083, which passed on the next commit.\n\n### Versions\n\nlinux-bionic-cuda10.2-py3.9-gcc7\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @nairbv @NicolasHug", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67447/comments", 
      "created_at": "2021-10-28T15:23:17Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67447/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67447", 
      "id": 1038648571, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "", 
          "id": 1313583792, 
          "name": "module: hub", 
          "node_id": "MDU6TGFiZWwxMzEzNTgzNzky", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20hub"
        }, 
        {
          "color": "bfdadc", 
          "default": false, 
          "description": "Denotes a (flaky) test currently skipped in CI.", 
          "id": 1679533716, 
          "name": "skipped", 
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67447/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z8496IT7", 
      "number": 67447, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67447/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67447/timeline", 
      "title": "DISABLED test_set_dir (__main__.TestHub)", 
      "updated_at": "2021-10-28T15:24:22Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67447", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/31798555?v=4", 
        "events_url": "https://api.github.com/users/janeyx99/events{/privacy}", 
        "followers_url": "https://api.github.com/users/janeyx99/followers", 
        "following_url": "https://api.github.com/users/janeyx99/following{/other_user}", 
        "gists_url": "https://api.github.com/users/janeyx99/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/janeyx99", 
        "id": 31798555, 
        "login": "janeyx99", 
        "node_id": "MDQ6VXNlcjMxNzk4NTU1", 
        "organizations_url": "https://api.github.com/users/janeyx99/orgs", 
        "received_events_url": "https://api.github.com/users/janeyx99/received_events", 
        "repos_url": "https://api.github.com/users/janeyx99/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/janeyx99/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/janeyx99/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/janeyx99"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Test timed out here: https://github.com/pytorch/pytorch/runs/4059791464?check_suite_focus=true. \n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @lw @beauby @jjlilley", 
      "closed_at": null, 
      "comments": 3, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67604/comments", 
      "created_at": "2021-11-01T03:46:13Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67604/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67604", 
      "id": 1040726855, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }, 
        {
          "color": "f7e845", 
          "default": false, 
          "description": "Related to Tensorpipe RPC Agent", 
          "id": 1986434179, 
          "name": "module: tensorpipe", 
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Issues/PRs related distributed data parallel training", 
          "id": 2391777652, 
          "name": "module: ddp", 
          "node_id": "MDU6TGFiZWwyMzkxNzc3NjUy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20ddp"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67604/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-CDtH", 
      "number": 67604, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67604/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67604/timeline", 
      "title": "DISABLED test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)", 
      "updated_at": "2021-11-01T20:27:44Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67604", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Test timed out here: https://github.com/pytorch/pytorch/runs/4057157651?check_suite_focus=true.\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67605/comments", 
      "created_at": "2021-11-01T03:47:10Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67605/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67605", 
      "id": 1040727177, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "c5def5", 
          "default": false, 
          "description": "Add this issue/PR to JIT oncall triage queue", 
          "id": 679953983, 
          "name": "oncall: jit", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20jit"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer", 
          "id": 1536612774, 
          "name": "module: rpc", 
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67605/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-CDyJ", 
      "number": 67605, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67605/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67605/timeline", 
      "title": "DISABLED test_remote_script_udf (__main__.TensorPipeJitRpcTest)", 
      "updated_at": "2021-11-01T20:27:36Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67605", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "This is action following https://github.com/pytorch/pytorch/issues/67448--let's disable the test that seemed to have deadlocked. Using the discover tests feature and matching it up against the logs, it ends up being test_nested.\r\n\r\n```\r\n(pytorch) janeyx@janeyx-mbp pytorch % python test/test_multiprocessing_spawn.py --discover-tests\r\nForkTest.test_exception_all\r\nForkTest.test_exception_single\r\nForkTest.test_first_argument_index\r\nForkTest.test_nested\r\nForkTest.test_success\r\nForkTest.test_success_first_then_exception\r\nForkTest.test_success_non_blocking\r\nForkTest.test_terminate_exit\r\nForkTest.test_terminate_signal\r\nSpawnTest.test_exception_all\r\nSpawnTest.test_exception_raises\r\nSpawnTest.test_exception_single\r\nSpawnTest.test_first_argument_index\r\nSpawnTest.test_nested\r\nSpawnTest.test_process_exited\r\nSpawnTest.test_signal_raises\r\nSpawnTest.test_success\r\nSpawnTest.test_success_first_then_exception\r\nSpawnTest.test_success_non_blocking\r\nSpawnTest.test_terminate_exit\r\nSpawnTest.test_terminate_signal\r\n```", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/67881/comments", 
      "created_at": "2021-11-04T22:40:20Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/67881/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/67881", 
      "id": 1045274446, 
      "labels": [
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/67881/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-TZ9O", 
      "number": 67881, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/67881/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/67881/timeline", 
      "title": "DISABLED test_nested (__main__.ForkTest)", 
      "updated_at": "2021-11-05T16:09:46Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/67881", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/31798555?v=4", 
        "events_url": "https://api.github.com/users/janeyx99/events{/privacy}", 
        "followers_url": "https://api.github.com/users/janeyx99/followers", 
        "following_url": "https://api.github.com/users/janeyx99/following{/other_user}", 
        "gists_url": "https://api.github.com/users/janeyx99/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/janeyx99", 
        "id": 31798555, 
        "login": "janeyx99", 
        "node_id": "MDQ6VXNlcjMxNzk4NTU1", 
        "organizations_url": "https://api.github.com/users/janeyx99/orgs", 
        "received_events_url": "https://api.github.com/users/janeyx99/received_events", 
        "repos_url": "https://api.github.com/users/janeyx99/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/janeyx99/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/janeyx99/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/janeyx99"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "This test is failing consistently on _win-vs2019-cuda11.3-py3 / test (default, 2, 2, windows.8xlarge.nvidia.gpu) but apparently no other jobs. Failure snippet:\r\n\r\n```\r\n\u274c Failure: TestLinalgCUDA.test_addmm_baddbmm_overflow_cuda_float16\r\nTraceback (most recent call last):\r\n  File \"C:\\actions-runner\\_work\\pytorch\\pytorch\\build\\win_tmp\\build\\torch\\testing\\_internal\\common_device_type.py\", line 371, in instantiated_test\r\n    result = test(self, **param_kwargs)\r\n  File \"C:\\actions-runner\\_work\\pytorch\\pytorch\\build\\win_tmp\\build\\torch\\testing\\_internal\\common_device_type.py\", line 891, in only_fn\r\n    return fn(slf, *args, **kwargs)\r\n  File \"test_linalg.py\", line 6139, in test_addmm_baddbmm_overflow\r\n    self.assertTrue((out == 10000.).all())\r\nAssertionError: tensor(False, device='cuda:0') is not true\r\n```\r\n\r\nPlatforms: windows\r\n\r\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68125/comments", 
      "created_at": "2021-11-10T18:34:48Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68125/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68125", 
      "id": 1050172835, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Issues related to tests (not the torch.testing module)", 
          "id": 1300933336, 
          "name": "module: tests", 
          "node_id": "MDU6TGFiZWwxMzAwOTMzMzM2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tests"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68125/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-mF2j", 
      "number": 68125, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68125/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68125/timeline", 
      "title": "DISABLED test_addmm_baddbmm_overflow_cuda_float16 (__main__.TestLinalgCUDA)", 
      "updated_at": "2021-11-10T18:38:27Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68125", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Platforms: rocm\r\n\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9605//console\r\n\r\n```\r\n10:35:33 ======================================================================\r\n10:35:33 FAIL [0.421s]: test_nadam (__main__.TestOptim)\r\n10:35:33 ----------------------------------------------------------------------\r\n10:35:33 Traceback (most recent call last):\r\n10:35:33   File \"test_optim.py\", line 630, in test_nadam\r\n10:35:33     lambda weight, bias: optimizer(\r\n10:35:33   File \"test_optim.py\", line 231, in _test_basic_cases\r\n10:35:33     make_two_arg_constructor(constructor, maximize),\r\n10:35:33   File \"test_optim.py\", line 209, in _test_state_dict\r\n10:35:33     self.assertEqual(bias, bias_cuda)\r\n10:35:33   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1928, in assertEqual\r\n10:35:33     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))\r\n10:35:33 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 10) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.9073486328125e-05 (-1.0852036476135254 vs. -1.0851845741271973), which occurred at index 1.\r\n10:35:33 \r\n10:35:33 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @vincentqb @albanD @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68171/comments", 
      "created_at": "2021-11-11T14:17:12Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68171/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68171", 
      "id": 1051026090, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.optim", 
          "id": 1076923626, 
          "name": "module: optimizer", 
          "node_id": "MDU6TGFiZWwxMDc2OTIzNjI2", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20optimizer"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68171/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-pWKq", 
      "number": 68171, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68171/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68171/timeline", 
      "title": "DISABLED test_nadam (__main__.TestOptim)", 
      "updated_at": "2021-11-11T14:17:18Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68171", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Platforms: rocm\r\n\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9624//console\r\n\r\n12:34:17 ======================================================================\r\n12:34:17 FAIL [4.075s]: test_Conv2d_naive_groups_cuda_float16 (__main__.TestNNDeviceTypeCUDA)\r\n12:34:17 ----------------------------------------------------------------------\r\n12:34:17 Traceback (most recent call last):\r\n12:34:17   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1447, in wrapper\r\n12:34:17     method(*args, **kwargs)\r\n12:34:17   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1447, in wrapper\r\n12:34:17     method(*args, **kwargs)\r\n12:34:17   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py\", line 371, in instantiated_test\r\n12:34:17     result = test(self, **param_kwargs)\r\n12:34:17   File \"test_nn.py\", line 16621, in test_Conv2d_naive_groups\r\n12:34:17     self.assertEqual(output, torch.cat([output1, output2], 1))\r\n12:34:17   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1928, in assertEqual\r\n12:34:17     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))\r\n12:34:17 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0.001 and atol=1e-05, found 34 element(s) (out of 128) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0009765625 (-0.51953125 vs. -0.5205078125), which occurred at index (0, 3, 0, 2).\r\n12:34:17 \r\n12:34:17 ----------------------------------------------------------------------\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @walterddr @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68172/comments", 
      "created_at": "2021-11-11T14:18:36Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68172/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68172", 
      "id": 1051027463, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Related to torch.nn", 
          "id": 1076922764, 
          "name": "module: nn", 
          "node_id": "MDU6TGFiZWwxMDc2OTIyNzY0", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20nn"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68172/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-pWgH", 
      "number": 68172, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68172/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68172/timeline", 
      "title": "DISABLED test_Conv2d_naive_groups_cuda_float16 (__main__.TestNNDeviceTypeCUDA)", 
      "updated_at": "2021-11-11T14:18:40Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68172", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Platforms: rocm\r\n\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4865//console\r\n\r\n```\r\n13:00:51 ======================================================================\r\n13:00:51 ERROR [105.046s]: test_ddp_sync_bn_training_vs_eval (__main__.TestDistBackendWithSpawn)\r\n13:00:51 ----------------------------------------------------------------------\r\n13:00:51 Traceback (most recent call last):\r\n13:00:51   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 457, in wrapper\r\n13:00:51     self._join_processes(fn)\r\n13:00:51   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 676, in _join_processes\r\n13:00:51     self._check_return_codes(elapsed_time)\r\n13:00:51   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 728, in _check_return_codes\r\n13:00:51     i, elapsed_time\r\n13:00:51 RuntimeError: Process 0 terminated or timed out after 105.0231831073761 seconds\r\n```\r\n\r\nHappening consistently after https://github.com/pytorch/pytorch/pull/67445\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 16, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68173/comments", 
      "created_at": "2021-11-11T14:19:56Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68173/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68173", 
      "id": 1051028810, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Problem is a flaky test in CI", 
          "id": 1301397902, 
          "name": "module: flaky-tests", 
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68173/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-pW1K", 
      "number": 68173, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68173/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68173/timeline", 
      "title": "DISABLED test_ddp_sync_bn_training_vs_eval (__main__.TestDistBackendWithSpawn)", 
      "updated_at": "2021-11-12T20:30:38Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68173", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Platforms: rocm\r\n\r\nSee https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=rocm.*distributed \r\nFor example, see https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4890//console\r\nSeems to be caused by https://github.com/pytorch/pytorch/pull/67901\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68189/comments", 
      "created_at": "2021-11-11T19:05:54Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68189/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68189", 
      "id": 1051276707, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }, 
        {
          "color": "006b75", 
          "default": false, 
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module", 
          "id": 1301347167, 
          "name": "triaged", 
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68189/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-qTWj", 
      "number": 68189, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68189/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68189/timeline", 
      "title": "DISABLED test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)", 
      "updated_at": "2021-11-11T19:09:05Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68189", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/2453524?v=4", 
        "events_url": "https://api.github.com/users/malfet/events{/privacy}", 
        "followers_url": "https://api.github.com/users/malfet/followers", 
        "following_url": "https://api.github.com/users/malfet/following{/other_user}", 
        "gists_url": "https://api.github.com/users/malfet/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/malfet", 
        "id": 2453524, 
        "login": "malfet", 
        "node_id": "MDQ6VXNlcjI0NTM1MjQ=", 
        "organizations_url": "https://api.github.com/users/malfet/orgs", 
        "received_events_url": "https://api.github.com/users/malfet/received_events", 
        "repos_url": "https://api.github.com/users/malfet/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/malfet/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/malfet/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/malfet"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Platforms: rocm\r\n\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4942//console\r\n\r\n```\r\n22:20:08 ----------------------------------------------------------------------\r\n22:20:08 Test results will be stored in test-reports/dist-gloo/distributed.test_distributed_spawn\r\n22:20:08   test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn) ... [W Module.cpp:494] Warning: Disabling benchmark mode for MIOpen is NOT supported. Overriding value to True (function operator())\r\n22:20:20 munmap_chunk(): invalid pointer\r\n22:20:20 SIGABRT(6), PID: 17317, Thread 17317: \r\n22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\n22:20:20 frame #1: c10::FatalSignalHandler::fatalSignalHandler(int) + 0x152 (0x7f55e78278c2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\n22:20:20 frame #2: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #3: gsignal + 0xc7 (0x7f56275a2fb7 in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #4: abort + 0x141 (0x7f56275a4921 in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #5: <unknown function> + 0x89967 (0x7f56275ed967 in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #6: <unknown function> + 0x909da (0x7f56275f49da in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #7: cfree + 0x58c (0x7f56275fbfbc in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #8: <unknown function> + 0x5159ec5 (0x7f5619d1eec5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #9: <unknown function> + 0x514aa79 (0x7f5619d0fa79 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #10: <unknown function> + 0x514aa89 (0x7f5619d0fa89 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #11: <unknown function> + 0x51514b8 (0x7f5619d164b8 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #12: <unknown function> + 0x51393b2 (0x7f5619cfe3b2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #13: torch::autograd::profiler::disableProfiler() + 0x2d7 (0x7f5617bd2347 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #14: <unknown function> + 0xc20027 (0x7f561ee37027 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\n22:20:20 frame #15: <unknown function> + 0x8a3baf (0x7f561eababaf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\n22:20:20 frame #16: <unknown function> + 0x18327c (0x56210da8127c in /opt/conda/bin/python3.6)\r\n22:20:20 frame #17: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #18: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #19: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #20: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #21: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #22: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #23: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #24: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #25: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #26: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #27: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #28: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #29: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #30: <unknown function> + 0x173044 (0x56210da71044 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #31: _PyObject_FastCallDict + 0x17c (0x56210da2f28c in /opt/conda/bin/python3.6)\r\n22:20:20 frame #32: PyObject_CallFunctionObjArgs + 0xec (0x56210da38bcc in /opt/conda/bin/python3.6)\r\n22:20:20 frame #33: _PyEval_EvalFrameDefault + 0x1b6e (0x56210da9fb5e in /opt/conda/bin/python3.6)\r\n22:20:20 frame #34: <unknown function> + 0x130160 (0x56210da2e160 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #35: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #36: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #37: _PyEval_EvalFrameDefault + 0x1a2e (0x56210da9fa1e in /opt/conda/bin/python3.6)\r\n22:20:20 frame #38: <unknown function> + 0x130160 (0x56210da2e160 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #39: <unknown function> + 0x172a4b (0x56210da70a4b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #40: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)\r\n22:20:20 frame #41: _PyEval_EvalFrameDefault + 0x4b87 (0x56210daa2b77 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #42: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #43: <unknown function> + 0x172a4b (0x56210da70a4b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #44: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)\r\n22:20:20 frame #45: _PyEval_EvalFrameDefault + 0x4b87 (0x56210daa2b77 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #46: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #47: <unknown function> + 0x172a4b (0x56210da70a4b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #48: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)\r\n22:20:20 frame #49: _PyEval_EvalFrameDefault + 0x4b87 (0x56210daa2b77 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #50: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #51: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #52: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #53: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #54: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #55: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #56: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #57: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #58: <unknown function> + 0x130160 (0x56210da2e160 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #59: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)\r\n22:20:20 frame #60: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #61: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)\r\n22:20:20 frame #62: <unknown function> + 0x173044 (0x56210da71044 in /opt/conda/bin/python3.6)\r\n22:20:20 frame #63: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)\r\n22:20:20 \r\n22:20:20 SIGABRT(6), PID: 17317, Thread 17494: \r\n22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\n22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #2: ioctl + 0x7 (0x7f562767a317 in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #3: <unknown function> + 0xbb18 (0x7f55ba42db18 in /opt/rocm/hip/lib/../../lib/libhsakmt.so.1)\r\n22:20:20 frame #4: hsaKmtWaitOnMultipleEvents + 0xfa (0x7f55ba427d7a in /opt/rocm/hip/lib/../../lib/libhsakmt.so.1)\r\n22:20:20 frame #5: <unknown function> + 0x76185 (0x7f55ca305185 in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)\r\n22:20:20 frame #6: <unknown function> + 0x57c4e (0x7f55ca2e6c4e in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)\r\n22:20:20 frame #7: <unknown function> + 0x6e502 (0x7f55ca2fd502 in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)\r\n22:20:20 frame #8: <unknown function> + 0x16497 (0x7f55ca2a5497 in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)\r\n22:20:20 frame #9: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #10: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 \r\n22:20:20 SIGABRT(6), PID: 17317, Thread 17497: \r\n22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\n22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #2: epoll_wait + 0x57 (0x7f5627685a47 in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 frame #3: gloo::transport::tcp::Loop::run() + 0x62 (0x7f5619b991e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #4: <unknown function> + 0xc9039 (0x7f55e773f039 in /opt/conda/lib/libstdc++.so.6)\r\n22:20:20 frame #5: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #6: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 \r\n22:20:20 SIGABRT(6), PID: 17317, Thread 17503: \r\n22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\n22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #2: pthread_cond_wait + 0x243 (0x7f5627962ad3 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #3: std::condition_variable::wait(std::unique_lock<std::mutex>&) + 0x9 (0x7f55e773b399 in /opt/conda/lib/libstdc++.so.6)\r\n22:20:20 frame #4: c10d::ProcessGroupGloo::runLoop(int) + 0x211 (0x7f56183812b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #5: <unknown function> + 0xc9039 (0x7f55e773f039 in /opt/conda/lib/libstdc++.so.6)\r\n22:20:20 frame #6: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #7: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 \r\n22:20:20 SIGABRT(6), PID: 17317, Thread 17504: \r\n22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\n22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #2: pthread_cond_wait + 0x243 (0x7f5627962ad3 in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #3: std::condition_variable::wait(std::unique_lock<std::mutex>&) + 0x9 (0x7f55e773b399 in /opt/conda/lib/libstdc++.so.6)\r\n22:20:20 frame #4: c10d::ProcessGroupGloo::runLoop(int) + 0x211 (0x7f56183812b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\n22:20:20 frame #5: <unknown function> + 0xc9039 (0x7f55e773f039 in /opt/conda/lib/libstdc++.so.6)\r\n22:20:20 frame #6: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)\r\n22:20:20 frame #7: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)\r\n22:20:20 \r\n22:21:20 ERROR:torch.testing._internal.common_distributed:Caught exception: \r\n22:21:20 Traceback (most recent call last):\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 575, in run_test\r\n22:21:20     getattr(self, test_name)()\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 459, in wrapper\r\n22:21:20     fn()\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 112, in wrapper\r\n22:21:20     return func(*args, **kwargs)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:20     return func(*args, **kwargs)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:20     return func(*args, **kwargs)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5710, in test_ddp_profiling_torch_profiler\r\n22:21:20     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5671, in _test_ddp_profiling\r\n22:21:20     find_unused_parameters=True,\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 601, in __init__\r\n22:21:20     dist._verify_params_across_processes(self.process_group, parameters)\r\n22:21:20 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 60000ms for send operation to complete\r\n22:21:20  exiting process 0 with exit code: 10\r\n22:21:20 ERROR:torch.testing._internal.common_distributed:Caught exception: \r\n22:21:20 Traceback (most recent call last):\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 575, in run_test\r\n22:21:20     getattr(self, test_name)()\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 459, in wrapper\r\n22:21:20     fn()\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 112, in wrapper\r\n22:21:20     return func(*args, **kwargs)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:20     return func(*args, **kwargs)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:20     return func(*args, **kwargs)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5710, in test_ddp_profiling_torch_profiler\r\n22:21:20     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5671, in _test_ddp_profiling\r\n22:21:20     find_unused_parameters=True,\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 603, in __init__\r\n22:21:20     self._sync_params_and_buffers(authoritative_rank=0)\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 625, in _sync_params_and_buffers\r\n22:21:20     module_states, self.broadcast_bucket_size, authoritative_rank\r\n22:21:20   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 1420, in _distributed_broadcast_coalesced\r\n22:21:20     self.process_group, tensors, buffer_size, authoritative_rank\r\n22:21:20 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 60000ms for recv operation to complete\r\n22:21:20  exiting process 1 with exit code: 10\r\n22:21:22 Process 0 terminated with exit code 10, terminating remaining processes.\r\n22:21:22 ERROR (74.079s)\r\n22:21:22 \r\n22:21:22 ======================================================================\r\n22:21:22 ERROR [74.079s]: test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)\r\n22:21:22 ----------------------------------------------------------------------\r\n22:21:22 Traceback (most recent call last):\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 457, in wrapper\r\n22:21:22     self._join_processes(fn)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 676, in _join_processes\r\n22:21:22     self._check_return_codes(elapsed_time)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 721, in _check_return_codes\r\n22:21:22     raise RuntimeError(error)\r\n22:21:22 RuntimeError: Process 0 exited with error code 10 and exception:\r\n22:21:22 Traceback (most recent call last):\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 575, in run_test\r\n22:21:22     getattr(self, test_name)()\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 459, in wrapper\r\n22:21:22     fn()\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 112, in wrapper\r\n22:21:22     return func(*args, **kwargs)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:22     return func(*args, **kwargs)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:22     return func(*args, **kwargs)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5710, in test_ddp_profiling_torch_profiler\r\n22:21:22     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5671, in _test_ddp_profiling\r\n22:21:22     find_unused_parameters=True,\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 601, in __init__\r\n22:21:22     dist._verify_params_across_processes(self.process_group, parameters)\r\n22:21:22 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 60000ms for send operation to complete\r\n22:21:22 \r\n22:21:22 Process 1 exited with error code 10 and exception:\r\n22:21:22 Traceback (most recent call last):\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 575, in run_test\r\n22:21:22     getattr(self, test_name)()\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 459, in wrapper\r\n22:21:22     fn()\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 112, in wrapper\r\n22:21:22     return func(*args, **kwargs)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:22     return func(*args, **kwargs)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2994, in wrapper\r\n22:21:22     return func(*args, **kwargs)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5710, in test_ddp_profiling_torch_profiler\r\n22:21:22     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py\", line 5671, in _test_ddp_profiling\r\n22:21:22     find_unused_parameters=True,\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 603, in __init__\r\n22:21:22     self._sync_params_and_buffers(authoritative_rank=0)\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 625, in _sync_params_and_buffers\r\n22:21:22     module_states, self.broadcast_bucket_size, authoritative_rank\r\n22:21:22   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py\", line 1420, in _distributed_broadcast_coalesced\r\n22:21:22     self.process_group, tensors, buffer_size, authoritative_rank\r\n22:21:22 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 60000ms for recv operation to complete\r\n22:21:22 \r\n22:21:22 \r\n22:21:22 \r\n22:21:23 ----------------------------------------------------------------------\r\n22:21:23 Ran 1 test in 74.080s\r\n22:21:23 \r\n22:21:23 FAILED (errors=1)\r\n```\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 4, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68222/comments", 
      "created_at": "2021-11-11T23:34:06Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68222/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68222", 
      "id": 1051445510, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68222/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-q8kG", 
      "number": 68222, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68222/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68222/timeline", 
      "title": "DISABLED test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)", 
      "updated_at": "2021-11-11T23:57:50Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68222", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }, 
    {
      "active_lock_reason": null, 
      "assignee": null, 
      "assignees": [], 
      "author_association": "CONTRIBUTOR", 
      "body": "Platforms: rocm\r\n\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/5283//console\r\n\r\n```\r\n15:47:14 ======================================================================\r\n15:47:14 FAIL [4.027s]: test_nccl_barrier_timeout_new_group_non_member (__main__.CommTest)\r\n15:47:14 ----------------------------------------------------------------------\r\n15:47:14 Traceback (most recent call last):\r\n15:47:14   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 458, in wrapper\r\n15:47:14     self._join_processes(fn)\r\n15:47:14   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 677, in _join_processes\r\n15:47:14     self._check_return_codes(elapsed_time)\r\n15:47:14   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 736, in _check_return_codes\r\n15:47:14     i, first_process.exitcode, p.exitcode\r\n15:47:14   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 2065, in assertEqual\r\n15:47:14     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))\r\n15:47:14 AssertionError: False is not true : Scalars failed to compare as equal! -6 != 0\r\n15:47:14 Expect process 1 exit code to match Process 0 exit code of 0, but got -6\r\n15:47:14 \r\n15:47:14 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH", 
      "closed_at": null, 
      "comments": 1, 
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/68319/comments", 
      "created_at": "2021-11-13T17:29:38Z", 
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/68319/events", 
      "html_url": "https://github.com/pytorch/pytorch/issues/68319", 
      "id": 1052730484, 
      "labels": [
        {
          "color": "F22613", 
          "default": false, 
          "description": null, 
          "id": 443484135, 
          "name": "high priority", 
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority"
        }, 
        {
          "color": "cc317c", 
          "default": false, 
          "description": "", 
          "id": 466131885, 
          "name": "triage review", 
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "Add this issue/PR to distributed oncall triage queue", 
          "id": 679953883, 
          "name": "oncall: distributed", 
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed"
        }, 
        {
          "color": "f7e101", 
          "default": false, 
          "description": "AMD GPU support for Pytorch", 
          "id": 1078897659, 
          "name": "module: rocm", 
          "node_id": "MDU6TGFiZWwxMDc4ODk3NjU5", 
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rocm"
        }
      ], 
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/68319/labels{/name}", 
      "locked": false, 
      "milestone": null, 
      "node_id": "I_kwDOA-j9z84-v2R0", 
      "number": 68319, 
      "performed_via_github_app": null, 
      "reactions": {
        "+1": 0, 
        "-1": 0, 
        "confused": 0, 
        "eyes": 0, 
        "heart": 0, 
        "hooray": 0, 
        "laugh": 0, 
        "rocket": 0, 
        "total_count": 0, 
        "url": "https://api.github.com/repos/pytorch/pytorch/issues/68319/reactions"
      }, 
      "repository_url": "https://api.github.com/repos/pytorch/pytorch", 
      "score": 0.0, 
      "state": "open", 
      "timeline_url": "https://api.github.com/repos/pytorch/pytorch/issues/68319/timeline", 
      "title": "DISABLED test_nccl_barrier_timeout_new_group_non_member (__main__.CommTest)", 
      "updated_at": "2021-11-13T17:30:07Z", 
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/68319", 
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/38511765?v=4", 
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}", 
        "followers_url": "https://api.github.com/users/mruberry/followers", 
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}", 
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}", 
        "gravatar_id": "", 
        "html_url": "https://github.com/mruberry", 
        "id": 38511765, 
        "login": "mruberry", 
        "node_id": "MDQ6VXNlcjM4NTExNzY1", 
        "organizations_url": "https://api.github.com/users/mruberry/orgs", 
        "received_events_url": "https://api.github.com/users/mruberry/received_events", 
        "repos_url": "https://api.github.com/users/mruberry/repos", 
        "site_admin": false, 
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/mruberry"
      }
    }
  ], 
  "total_count": 64
}